server: 
  port: 8081

spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/backend?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa: 
    database: mysql
    generate-ddl: true
    show-sql: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    mode: HTML

logging:
  config: classpath:logback-local.xml
